### ISSUE TITLE
Cannot Detect Dashboard Provided in Config

### ISSUE THREAD

**Issue by joejean** [parvez/snapshot_for_kibana#1]
Hi @parvez, 
Thanks for this tool. I'm trying to use it but it is  not working properly. 
- When I try to schedule a new snapshot the dashboard dropdown does not list the dashboard I have provided in the config. And it also says unable to add. My config file looks as follow:

```
{
  "app_port": 8080,
  "app_dir": "/deploy",
  "os_type": "linux",
  "phantomjs": {
    "wait_seconds": "30"
  },
  "dashboard_url": "http://localhost:5601/app/kibana#/dashboard/",
  "dashboards_list_url": "http://localhost:5601/app/kibana#/dashboard/For-Cyber-Security",
  "basic_auth_users": [
    {"user": "u1", "password": "p1"},
    {"user": "u2", "password": "p2"}
  ]
}
```

I have the following error in the log:
`2016-06-30T07:59:17.071Z - error: (helper_logger.js 102) [/api/dashboards] []error: {"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect"}`

Do you know how to fix this? Thanks

**Comment by parvez** [comment]
The list url is the search query for all dashboards. The list of dashboards would be show in the dropdown using this url:

  "dashboards_list_url": "http://localhost:5601/elasticsearch/.kibana/dashboard/_search?size=100",

The url you will notice is the direct api call to get the json list of the dashboards.
Also can you check if the app has access to kibana?
