### ISSUE TITLE
Minor issue when data directory does not exist

### ISSUE THREAD

**Issue by eperry** [parvez/snapshot_for_kibana#10]
Minor issue: When the data directory does not exist it throws this ajax error on the font page, untill the first image is rendered ( I did not run in docker just off of the github clone) 

![screenshot from 2016-08-25 08-42-18](https://cloud.githubusercontent.com/assets/6170692/17969465/2842e9d6-6aa0-11e6-9524-67c5ca9ee9e2.png)

Fantastic app, THANKS!

oh simple fix was to mkdir app/data    but be nice i the Javascript on the site did not throw an error or at least handled the error

**Comment by parvez** [comment]
Fixed!
