### ISSUE TITLE
Is there anyway to get the "Nav" bar to render or am I broke?

### ISSUE THREAD

**Issue by eperry** [parvez/snapshot_for_kibana#11]
At the top of my pages I see the Alternate text of the navigation tab you know Discover, Visuialize, Dashboard

Is this supposed to be this way or am I broken?

![screenshot from 2016-08-25 10-35-12](https://cloud.githubusercontent.com/assets/6170692/17973284/d939ed34-6aaf-11e6-8e83-da91c5fba0a9.png)

**Comment by eperry** [comment]
I added a pull to fix the issue. found if you add embed=true to the url it will disable the Nav bar. This skipping the rendering problem

**Comment by parvez** [comment]
I am not sure if the PR is the reason for the fix. I don't see this behavior. Can you show me how you set up your environment? Did you use Docker to start up the environment?
